apiVersion: v1
kind: Service
metadata:
  name: phonebookui
  labels:
    app: phonebook
    component: ui
spec:
  type: NodePort
  ports:
   - port: 8080
  selector:
   app: phonebook
   component: ui
